from source.python.sorting.insertion_sort import insertion_sort_inc as insertion_sort
from source.python.sorting.recursive_insertion_sort import recursive_insertion_sort
from source.python.sorting.selection_sort import selection_sort
